### ISSUE TITLE
Create an **empty** commit on master (and push **nothing else** there!)

### ISSUE THREAD

**Issue by webknjaz** [kpi-web-guild/django-girls-blog-siplyspell#5]
```console
git commit --allow-empty -m 'Initial commit'
git push origin master
```

And report here after that.

P.S. This is necessary for me to set up branch protection for this repo properly (I could do it but I figured it's a tiny bit of practice you can have).

**Comment by siplyspell** [comment]
question,


in previous issues I needed to configure Git.
Did this need to be installed on ubuntu and configured there too? or I can use Windows and Pycharm

**Comment by webknjaz** [comment]
All tasks assume that you'll use that GNU/Linux installation as your Python development environment so you need to do it there. Also, when learning Git, avoid GUIs as they hide the details of what's going on from you.

**Comment by siplyspell** [comment]
Okay

**Comment by siplyspell** [comment]
at the very beginning of the course I had the task to make the first commit, I made it with Windows and not with Linux, and now I cannot find it to execute on Linux. Can you help me ?

**Comment by l1storez** [comment]
clone your repo to Linux(git clone)

**Comment by webknjaz** [comment]
@siplyspell tasks @ https://github.com/kpi-web-guild/django-girls-blog-siplyspell/issues/2 should've made Git available on your system. After that, you should understand how to install software on Ubuntu via CLI.

I noticed that you've already created a commit that is not empty: https://github.com/kpi-web-guild/django-girls-blog-siplyspell/commit/7f0867dc31a8592e4888426a5c300972f299878b. The task was to have an empty commit as described in this issue instead. There was no task to create a readme.

FWIW that commit is enough for the purposes of this issue. I'll proceed and apply the branch protection now to the main branch so any other changes would need to go via PRs with dedicated branches.
